export const ROUTES = {
  HOME: '/home',
  LANDING: '/home',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_GIFT_CODE: '/admin/gift-code',
  ADMIN_DEPOSIT: '/admin/deposit',
  ADMIN_DEPOSIT_PROMOTION: '/admin/deposit-promotion',
  ADMIN_SHOP: '/admin/shop',
  ADMIN_USERS: '/admin/users',
  ADMIN_NEWS: '/admin/news',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_ADMINS: '/admin/admins',
  ADMIN_SUPPORT_CHANNELS: '/admin/support-channels',
  PROFILE: '/profile',
  LOGIN: '/login',
  SIGN_UP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  ORDER: '/order',
  DEPOSIT: '/deposit',
  TICKET_EXCHANGE: '/ticket-exchange',
  GIFT_CODE: '/gift-code',
  MARKET_PLACE: '/market-place',
  SUPPORT: '/support',
  NEWS: '/news',
};

export const AUTH_ROUTES = [ROUTES.LOGIN, ROUTES.SIGN_UP, ROUTES.FORGOT_PASSWORD];
